repos:
  - repo: https://github.com/zricethezav/gitleaks
    rev: v8.18.0
    hooks:
      - id: gitleaks
        args:
          - "--no-banner"
          - "--redact"
          - "--config=.gitleaks.toml"
        stages: [commit, push]