extends: ["spectral:oas"]
rules:
  oas3-api-servers: off
  info-contact: off
  operation-operationId-unique: warn
  operation-tags: warn
  operation-security-defined:
    description: Authenticated operations must declare security requirements
    severity: error
    given: $.paths[*][*]
    then:
      field: security
      function: truthy
  operation-401-response:
    description: Authenticated operations must define a 401 response
    severity: error
    given: $.paths[*][*][?(@.security && @.security.length > 0)]
    then:
      field: responses.401
      function: truthy
  operation-403-response:
    description: Authenticated operations must define a 403 response
    severity: error
    given: $.paths[*][*][?(@.security && @.security.length > 0)]
    then:
      field: responses.403
      function: truthy
  operation-success-response-has-json-schema:
    description: Successful responses must define application/json schema
    given: $.paths[*][*].responses[?(@property.match(/^(2|20|201|202|203)$/))]
    then:
      field: content.application/json.schema
      function: truthy
    severity: error

