# Lythaus (Asora) Analysis Options
#
# Enforces code quality, design system usage, and best practices.
# See: https://dart.dev/guides/language/analysis-options

include: package:flutter_lints/flutter.yaml

analyzer:
  errors:
    # Enforce design system usage
    todo: ignore
    deprecated_member_use: warning
    
    # Strict type checking
    invalid_assignment: error
    invalid_override: error
    
    # Code quality
    dead_code: warning
    always_put_control_body_on_new_line: ignore
    unused_import: warning
    unused_local_variable: info
    
  exclude:
    - lib/generated/**
    - build/**
    - .dart_tool/**
    
  language:
    strict-casts: true
    strict-inference: true
    strict-raw-types: true

linter:
  rules:
    # Error prevention
    - always_declare_return_types
    - avoid_empty_else
    - avoid_relative_lib_imports
    - avoid_slow_async_io
    - avoid_types_as_parameter_names
    - cancel_subscriptions
    - close_sinks
    - control_flow_in_finally
    - empty_statements
    - hash_and_equals
    - no_adjacent_strings_in_list
    - no_duplicate_case_values
    - prefer_void_to_null
    - test_types_in_equals
    - throw_in_finally
    - unnecessary_statements
    - unrelated_type_equality_checks
    - valid_regexps
    
    # Style
    - always_put_control_body_on_new_line
    - always_use_package_imports
    - avoid_print
    - avoid_returning_null_for_void
    - avoid_single_cascade_in_expression_statements
    - avoid_unnecessary_containers
    - camel_case_extensions
    - camel_case_types
    - constant_identifier_names
    - curly_braces_in_flow_control_structures
    - empty_catches
    - empty_constructor_bodies
    - library_names
    - library_prefixes
    - non_constant_identifier_names
    - prefer_const_constructors
    - prefer_const_constructors_in_immutables
    - prefer_const_declarations
    - prefer_const_literals_to_create_immutables
    - prefer_final_fields
    - prefer_final_locals
    - prefer_if_null_operators
    - prefer_is_empty
    - prefer_is_not_empty
    - prefer_single_quotes
    - require_trailing_commas
    - sized_box_for_whitespace
    - sort_child_properties_last
    - use_full_hex_values_for_flutter_colors
    - use_key_in_widget_constructors
    - use_rethrow_when_possible
    - use_super_parameters
    
    # Documentation
    - package_api_docs
    - public_member_api_docs
    
    # Pub
    - sort_pub_dependencies
    
    # Flutter-specific
    - avoid_web_libraries_in_flutter
    - use_build_context_synchronously

# Additional information about this file can be found at
# https://dart.dev/guides/language/analysis-options
