// Mocks generated by Mockito 5.4.6 from annotations
// in asora/test/features/admin/state/admin_config_diff_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:asora/features/admin/api/admin_api_client.dart' as _i3;
import 'package:asora/features/admin/domain/admin_config_models.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeAdminConfigEnvelope_0 extends _i1.SmartFake
    implements _i2.AdminConfigEnvelope {
  _FakeAdminConfigEnvelope_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeAdminAuditResponse_1 extends _i1.SmartFake
    implements _i2.AdminAuditResponse {
  _FakeAdminAuditResponse_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [AdminApiClient].
///
/// See the documentation for Mockito's code generation for more information.
class MockAdminApiClient extends _i1.Mock implements _i3.AdminApiClient {
  MockAdminApiClient() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.AdminConfigEnvelope> getConfig() =>
      (super.noSuchMethod(
            Invocation.method(#getConfig, []),
            returnValue: _i4.Future<_i2.AdminConfigEnvelope>.value(
              _FakeAdminConfigEnvelope_0(
                this,
                Invocation.method(#getConfig, []),
              ),
            ),
          )
          as _i4.Future<_i2.AdminConfigEnvelope>);

  @override
  _i4.Future<_i2.AdminConfigEnvelope> updateConfig({
    required int? expectedVersion,
    required _i2.AdminConfig? config,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfig, [], {
              #expectedVersion: expectedVersion,
              #config: config,
            }),
            returnValue: _i4.Future<_i2.AdminConfigEnvelope>.value(
              _FakeAdminConfigEnvelope_0(
                this,
                Invocation.method(#updateConfig, [], {
                  #expectedVersion: expectedVersion,
                  #config: config,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AdminConfigEnvelope>);

  @override
  _i4.Future<_i2.AdminConfigEnvelope> updateConfigPatch({
    required int? expectedVersion,
    required _i2.AdminConfig? currentConfig,
    required Map<String, dynamic>? patch,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#updateConfigPatch, [], {
              #expectedVersion: expectedVersion,
              #currentConfig: currentConfig,
              #patch: patch,
            }),
            returnValue: _i4.Future<_i2.AdminConfigEnvelope>.value(
              _FakeAdminConfigEnvelope_0(
                this,
                Invocation.method(#updateConfigPatch, [], {
                  #expectedVersion: expectedVersion,
                  #currentConfig: currentConfig,
                  #patch: patch,
                }),
              ),
            ),
          )
          as _i4.Future<_i2.AdminConfigEnvelope>);

  @override
  _i4.Future<_i2.AdminAuditResponse> getAuditLog({int? limit = 50}) =>
      (super.noSuchMethod(
            Invocation.method(#getAuditLog, [], {#limit: limit}),
            returnValue: _i4.Future<_i2.AdminAuditResponse>.value(
              _FakeAdminAuditResponse_1(
                this,
                Invocation.method(#getAuditLog, [], {#limit: limit}),
              ),
            ),
          )
          as _i4.Future<_i2.AdminAuditResponse>);
}
