name = "feed-cache-worker"
main = "cloudflare/worker.ts"
compatibility_date = "2024-01-01"

[vars]
FEED_CACHE_ENABLED = "true"

# Configure your zone and route(s) here. Example:
# routes = [
#   { pattern = "api.your-domain.com/api/*", zone_name = "your-domain.com" }
# ]

