name: Deploy Azure Function App

on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'Target environment'
        required: true
        default: 'dev'
        type: choice
        options: [dev, staging, production]
      function_app_name:
        description: 'Optional override for Function App name (if you need to target a different app)'
        required: false
        default: ''
      force_deploy:
        description: 'Ignore change detection'
        required: false
        default: false
        type: boolean
  workflow_call:
    inputs:
      environment:
        required: true
        type: string
      force_deploy:
        required: false
        type: boolean

# Required for OIDC authentication with Azure
permissions:
  contents: read
  id-token: write

concurrency:
  group: functionapp-${{ inputs.environment }}
  cancel-in-progress: true

env:
  NODE_VERSION: '20'
  FUNCTIONS_WORKER_RUNTIME: 'node'
  WORKING_DIR: 'functions'

jobs:
  infra:
    uses: ./.github/workflows/infra.yml
    with:
      environment: ${{ inputs.environment }}
    secrets: inherit

  deploy:
    name: Build and deploy
    runs-on: ubuntu-latest
    needs: infra
    environment: ${{ inputs.environment }}
    env:
      AZURE_CLIENT_ID: ${{ secrets.AZURE_CLIENT_ID }}
      AZURE_TENANT_ID: ${{ secrets.AZURE_TENANT_ID }}
      AZURE_SUBSCRIPTION_ID: ${{ secrets.AZURE_SUBSCRIPTION_ID }}

    steps:
      - uses: actions/checkout@v4

      - name: Resolve environment config
        run: |
          if [ -n "${{ inputs.function_app_name }}" ] && [ "${{ inputs.function_app_name }}" != "" ]; then
            echo "Using override AZURE_FUNCTIONAPP_NAME=${{ inputs.function_app_name }}"
            echo "AZURE_FUNCTIONAPP_NAME=${{ inputs.function_app_name }}" >> $GITHUB_ENV
            # keep existing RG mapping for environment
            case "${{ inputs.environment }}" in
              dev)
                echo "AZURE_RESOURCE_GROUP=asora-psql-flex" >> $GITHUB_ENV
                ;;
              staging)
                echo "AZURE_RESOURCE_GROUP=asora-staging" >> $GITHUB_ENV
                ;;
              production)
                echo "AZURE_RESOURCE_GROUP=asora-production" >> $GITHUB_ENV
                ;;
            esac
          else
            case "${{ inputs.environment }}" in
              dev)
                echo "AZURE_FUNCTIONAPP_NAME=asora-function-dev" >> $GITHUB_ENV
                echo "AZURE_RESOURCE_GROUP=asora-psql-flex" >> $GITHUB_ENV
                ;;
              staging)
                # Prefer the Terraform-created naming pattern (asora-staging-function). Keep legacy asora-function-staging as an accepted override.
                echo "AZURE_FUNCTIONAPP_NAME=asora-staging-function" >> $GITHUB_ENV
                echo "AZURE_RESOURCE_GROUP=asora-staging" >> $GITHUB_ENV
                ;;
              production)
                echo "AZURE_FUNCTIONAPP_NAME=asora-function-production" >> $GITHUB_ENV
                echo "AZURE_RESOURCE_GROUP=asora-production" >> $GITHUB_ENV
                ;;
            esac
          fi

      - name: Enforce branch for production
        if: ${{ inputs.environment == 'production' && github.ref != 'refs/heads/main' }}
        run: |
          echo "Production deploys must run from main. Current ref: ${{ github.ref }}."
          exit 1

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'
          cache-dependency-path: ${{ env.WORKING_DIR }}/package-lock.json

      - name: Install Azure Functions Core Tools v4
        run: npm i -g azure-functions-core-tools@4 --unsafe-perm true

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id: ${{ env.AZURE_CLIENT_ID }}
          tenant-id: ${{ env.AZURE_TENANT_ID }}
          subscription-id: ${{ env.AZURE_SUBSCRIPTION_ID }}

      - name: Show Azure context
        run: az account show -o table

      - name: Auto-detect Function App name and Resource Group
        run: |
          echo "Attempting to auto-detect Function App and resource group (if necessary)..."
          # inputs.environment is available at runtime; use it to try common name patterns
          ENV_NAME="${{ inputs.environment }}"

          # If AZURE_FUNCTIONAPP_NAME or AZURE_RESOURCE_GROUP are not yet set (should be set by Resolve step), ensure variables are defined
          AZURE_FUNCTIONAPP_NAME="${AZURE_FUNCTIONAPP_NAME:-}"
          AZURE_RESOURCE_GROUP="${AZURE_RESOURCE_GROUP:-}"

          try_show() {
            local name="$1" rg="$2"
            if [ -z "$name" ]; then
              return 1
            fi
            if [ -n "$rg" ]; then
              az functionapp show --name "$name" --resource-group "$rg" -o none 2>/dev/null && return 0 || return 1
            else
              az functionapp show --name "$name" -o none 2>/dev/null && return 0 || return 1
            fi
          }

          # First quick check: current values
          if try_show "$AZURE_FUNCTIONAPP_NAME" "$AZURE_RESOURCE_GROUP"; then
            echo "Found Function App '$AZURE_FUNCTIONAPP_NAME' in RG '$AZURE_RESOURCE_GROUP'"
            exit 0
          fi

          # Search subscription for the exact name (maybe RG was wrong)
          if [ -n "$AZURE_FUNCTIONAPP_NAME" ]; then
            FOUND_RG=$(az functionapp list --query "[?name=='$AZURE_FUNCTIONAPP_NAME'].resourceGroup | [0]" -o tsv || true)
            if [ -n "$FOUND_RG" ]; then
              echo "Auto-detected resource group: $FOUND_RG for $AZURE_FUNCTIONAPP_NAME"
              echo "AZURE_RESOURCE_GROUP=$FOUND_RG" >> $GITHUB_ENV
              export AZURE_RESOURCE_GROUP="$FOUND_RG"
              exit 0
            fi
          fi

          # Try common name patterns: asora-<env>-function and asora-function-<env>
          CANDIDATES=("asora-${ENV_NAME}-function" "asora-function-${ENV_NAME}" "asora-${ENV_NAME}" "${ENV_NAME}-function")
          for cand in "${CANDIDATES[@]}"; do
            echo "Trying candidate name: $cand"
            RG=$(az functionapp list --query "[?name=='$cand'].resourceGroup | [0]" -o tsv || true)
            if [ -n "$RG" ]; then
              echo "Found Function App '$cand' in resource group '$RG'"
              echo "AZURE_FUNCTIONAPP_NAME=$cand" >> $GITHUB_ENV
              echo "AZURE_RESOURCE_GROUP=$RG" >> $GITHUB_ENV
              export AZURE_FUNCTIONAPP_NAME="$cand"
              export AZURE_RESOURCE_GROUP="$RG"
              exit 0
            fi
          done

          # Last resort: try to find any function app containing the env name (returns first match)
          ANY=$(az functionapp list --query "[?contains(name, '${ENV_NAME}')].{name:name,rg:resourceGroup} | [0]" -o tsv 2>/dev/null || true)
          if [ -n "$ANY" ]; then
            # ANY will be "name\trg" when output as tsv; split into two
            NAME_FOUND=$(echo "$ANY" | awk '{print $1}')
            RG_FOUND=$(echo "$ANY" | awk '{print $2}')
            if [ -n "$NAME_FOUND" ] && [ -n "$RG_FOUND" ]; then
              echo "Auto-detected Function App '$NAME_FOUND' in resource group '$RG_FOUND'"
              echo "AZURE_FUNCTIONAPP_NAME=$NAME_FOUND" >> $GITHUB_ENV
              echo "AZURE_RESOURCE_GROUP=$RG_FOUND" >> $GITHUB_ENV
              export AZURE_FUNCTIONAPP_NAME="$NAME_FOUND"
              export AZURE_RESOURCE_GROUP="$RG_FOUND"
              exit 0
            fi
          fi

          echo "ERROR: Could not find Function App '$AZURE_FUNCTIONAPP_NAME' in resource group '$AZURE_RESOURCE_GROUP' or with common name patterns."
          echo "Please verify the AZURE_FUNCTIONAPP_NAME, AZURE_RESOURCE_GROUP, and AZURE_SUBSCRIPTION_ID are correct."
          exit 1


      - name: Configure Function App for Node 20
        run: |
          echo "Configuring Function App runtime and app settings for Node 20 and pinning Oryx build versions..."

          # Helper to test for app existence
          app_exists() {
            az functionapp show --name "$1" --resource-group "$2" -o none 2>/dev/null
          }

          if app_exists "$AZURE_FUNCTIONAPP_NAME" "$AZURE_RESOURCE_GROUP"; then
            echo "Found $AZURE_FUNCTIONAPP_NAME in $AZURE_RESOURCE_GROUP"
          else
            echo "Warning: $AZURE_FUNCTIONAPP_NAME not found in $AZURE_RESOURCE_GROUP. Attempting to auto-detect in subscription..."
            # Try to auto-detect RG for exact name
            FOUND_RG=$(az functionapp list --query "[?name=='$AZURE_FUNCTIONAPP_NAME'].resourceGroup | [0]" -o tsv || true)
            if [ -n "$FOUND_RG" ]; then
              echo "Auto-detected resource group: $FOUND_RG for $AZURE_FUNCTIONAPP_NAME"
              echo "AZURE_RESOURCE_GROUP=$FOUND_RG" >> $GITHUB_ENV
              export AZURE_RESOURCE_GROUP="$FOUND_RG"
            else
              # Try common name patterns (reverse variations)
              ENV_NAME="${{ inputs.environment }}"
              CANDIDATES=("asora-${ENV_NAME}-function" "asora-function-${ENV_NAME}" "asora-${ENV_NAME}" "${ENV_NAME}-function")
              MATCHED=0
              for cand in "${CANDIDATES[@]}"; do
                RG=$(az functionapp list --query "[?name=='$cand'].resourceGroup | [0]" -o tsv || true)
                if [ -n "$RG" ]; then
                  echo "Found candidate Function App '$cand' in RG '$RG'"
                  echo "AZURE_FUNCTIONAPP_NAME=$cand" >> $GITHUB_ENV
                  echo "AZURE_RESOURCE_GROUP=$RG" >> $GITHUB_ENV
                  export AZURE_FUNCTIONAPP_NAME="$cand"
                  export AZURE_RESOURCE_GROUP="$RG"
                  MATCHED=1
                  break
                fi
              done
              if [ "$MATCHED" -eq 0 ]; then
                echo "ERROR: Function App '$AZURE_FUNCTIONAPP_NAME' not found and no common candidates matched." >&2
                echo "Please verify AZURE_FUNCTIONAPP_NAME/AZURE_RESOURCE_GROUP or pass 'function_app_name' override to the workflow." >&2
                exit 1
              fi
            fi
          fi

          # Now apply runtime and appsettings safely
          az functionapp config set \
            --name "$AZURE_FUNCTIONAPP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --linux-fx-version "NODE|20-lts"

          az functionapp config appsettings set \
            --name "$AZURE_FUNCTIONAPP_NAME" \
            --resource-group "$AZURE_RESOURCE_GROUP" \
            --settings FUNCTIONS_EXTENSION_VERSION=~4 FUNCTIONS_WORKER_RUNTIME=node WEBSITE_NODE_DEFAULT_VERSION=~20

      - name: Build functions
        working-directory: ${{ env.WORKING_DIR }}
        env:
          HUSKY: "0"
          NPM_CONFIG_AUDIT: "false"
          NPM_CONFIG_FUND: "false"
        run: |
          npm ci
          npm run build || echo "No build script"

      - name: Verify Function App exists (pre-publish)
        run: |
          echo "Checking Azure subscription and target Function App"
          az account show --query "{name:name, user:user.name, id:id}" -o table || true
          echo "Looking for Function App: $AZURE_FUNCTIONAPP_NAME in RG: $AZURE_RESOURCE_GROUP"
          if az functionapp show --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" -o none 2>/dev/null; then
            echo "Found Function App: $AZURE_FUNCTIONAPP_NAME"
          else
            echo "ERROR: Function App '$AZURE_FUNCTIONAPP_NAME' not found in resource group '$AZURE_RESOURCE_GROUP'"
            echo "Listing Function Apps in $AZURE_RESOURCE_GROUP for debugging:"
            az functionapp list --resource-group "$AZURE_RESOURCE_GROUP" --query "[].{name:name, state:state, defaultHostName:defaultHostName}" -o table || true
            echo "Listing all Function Apps in subscription for extra context:"
            az functionapp list --query "[].{rg:resourceGroup, name:name, defaultHostName:defaultHostName}" -o table || true
            echo "Please verify the AZURE_FUNCTIONAPP_NAME, AZURE_RESOURCE_GROUP, and AZURE_SUBSCRIPTION_ID are correct and that the app exists."
            exit 1
          fi

      - name: Publish to Function App (local build)
        working-directory: ${{ env.WORKING_DIR }}
        run: |
          npm run build
          npm i -g azure-functions-core-tools@4 --unsafe-perm true
          npx azure-functions-core-tools@4 azure functionapp publish "$AZURE_FUNCTIONAPP_NAME" --javascript --build local --force

      - name: Resolve app URL
        id: url
        run: |
          HOST=$(az functionapp show --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" --query "defaultHostName" -o tsv)
          echo "app_url=https://$HOST" >> $GITHUB_OUTPUT
          echo "Deployed URL: https://$HOST"

      - name: Smoke check
        run: |
          URL="${{ steps.url.outputs.app_url }}"
          echo "Probing $URL ..."
          code=$(curl -s -o /dev/null -w "%{http_code}" "$URL")
          echo "HTTP $code"
          if [ "$code" = "000" ]; then
            echo "App not responding yet" && exit 1
          fi

      - name: Post-deployment validation
        run: |
          echo "Deployment completed successfully!"
          echo "Function App: $AZURE_FUNCTIONAPP_NAME"
          echo "Resource Group: $AZURE_RESOURCE_GROUP"
          echo "Checking linuxFxVersion and WEBSITE_NODE_DEFAULT_VERSION..."
          az functionapp config show --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" --query "linuxFxVersion" -o tsv || true
          az functionapp config appsettings list --name "$AZURE_FUNCTIONAPP_NAME" --resource-group "$AZURE_RESOURCE_GROUP" --query "[?name=='WEBSITE_NODE_DEFAULT_VERSION'].value" -o tsv || true

      - name: Key Vault references present
        run: |
          APP="$AZURE_FUNCTIONAPP_NAME"
          RG="$AZURE_RESOURCE_GROUP"
          req=("JWT_SECRET" "HIVE_TEXT_KEY" "HIVE_IMAGE_KEY" "HIVE_DEEPFAKE_KEY" "COSMOS_KEY" "POSTGRES_CONNECTION_STRING")
          for k in "${req[@]}"; do
            v=$(az functionapp config appsettings list -g "$RG" -n "$APP" --query "[?name=='$k'].value" -o tsv || true)
            if [[ "$v" != *"@Microsoft.KeyVault"* ]]; then
              echo "Missing Key Vault ref for $k"; exit 1
            fi
          done
          echo "Key Vault references OK"
