name: Flutter CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Format and analyze job
  format-and-analyze:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        cache: true
        cache-key: flutter-${{ runner.os }}
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Check formatting
      run: dart format --output=none --set-exit-if-changed .
      
    - name: Analyze code
      run: flutter analyze

  # Test job
  test:
    runs-on: ubuntu-latest
    needs: format-and-analyze
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: '3.32.8'
        cache: true
        cache-key: flutter-${{ runner.os }}
        
    - name: Get dependencies
      run: flutter pub get
      
    - name: Run tests
      run: flutter test
