name: OpenAPI

on:
  pull_request:
    paths:
      - 'api/openapi/**'
      - 'functions/**'
      - 'lib/**'
      - '.github/workflows/**'

jobs:
  contract:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run openapi:lint
      - run: npm run openapi:bundle
      - name: Upload bundled spec
        uses: actions/upload-artifact@v4
        with:
          name: openapi.json
          path: api/openapi/dist/openapi.json
