name: terraform
permissions:
  id-token: write
  contents: read

on:
  pull_request:
    paths: ["infra/**.tf"]
  push:
    branches: ["main"]

jobs:
  tf:
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v4

      - name: Azure login (OIDC)
        uses: azure/login@v2
        with:
          client-id:       ${{ secrets.AZURE_CLIENT_ID }}
          tenant-id:       ${{ secrets.AZURE_TENANT_ID }}
          subscription-id: ${{ secrets.AZURE_SUB_ID }}

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: 1.9.5

      - name: Init
        working-directory: infra
        run: |
          terraform init -reconfigure \
            -backend-config="resource_group_name=tfstate-rg" \
            -backend-config="storage_account_name=${{ secrets.TF_STATE_SA }}" \
            -backend-config="container_name=tfstate" \
            -backend-config="key=infra.dev.tfstate"

      - name: Plan
        run: terraform plan -out plan.out

      - name: Apply
        if: github.ref == 'refs/heads/main'
        run: terraform apply -auto-approve plan.out
