name: tests-and-coverage

on:
  pull_request:
    branches: [ main ]

permissions:
  contents: read
  pull-requests: write
  actions: read

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Cache pub dependencies
        uses: actions/cache@v4
        with:
          path: ~/.pub-cache
          key: ${{ runner.os }}-pub-${{ hashFiles('**/pubspec.lock') }}
          restore-keys: |
            ${{ runner.os }}-pub-

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.32.0'

      - name: Flutter pub get
        run: flutter pub get

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'
          cache-dependency-path: functions/package-lock.json

      - name: Install Functions dependencies
        working-directory: functions
        run: npm ci

      - name: Run tests with coverage
        run: ./scripts/test-with-coverage.sh

      - name: Upload coverage artifact
        uses: actions/upload-artifact@v4
        with:
          name: coverage-${{ github.sha }}
          path: coverage/

      - name: Extract overall coverage %
        id: cov
        run: |
          pct=$(grep -Eo '[0-9]+(\.[0-9]+)?%' coverage/coverage-summary.txt | head -n1 | tr -d '%')
          echo "pct=$pct" >> "$GITHUB_OUTPUT"

      - name: Comment coverage on PR
        if: ${{ github.event_name == 'pull_request' }}
        uses: actions/github-script@v7
        with:
          script: |
            const pct = core.getInput('pct', { required: true });
            const body = `**Coverage:** ${pct}%\n\nArtifact: \`${process.env.GITHUB_SHA}\``;
            await github.rest.issues.createComment({
              owner: context.repo.owner,
              repo: context.repo.repo,
              issue_number: context.issue.number,
              body
            });
          result-encoding: string
        env:
          pct: ${{ steps.cov.outputs.pct }}

      - name: Enforce ≥80% gate
        run: |
          req=80
          pct="${{ steps.cov.outputs.pct }}"
          awk -v p="$pct" -v r="$req" 'BEGIN{ exit (p+0 >= r) ? 0 : 1 }'